name: Deploy to Heroku (Cloud)
on:
  push:
    branches:
      - master
      - main
jobs:
  deploy:
    needs: [Linter, Unit-Tests]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.6.8 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "domestic-repairs-page"
          heroku_email: "ahmed233@uni.coventry.ac.uk"
          branch: "master"